version: '3.8'

services:
  manipulator-ui:
    build: .
    container_name: manipulator-ui
  
    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped
    networks:
      - vs_code_default

networks:
  vs_code_default:
    external: true